include ../../Makefile.conf

all: cert_main.class cert_register.class cert_request.class cert_request_offline.class cert_revoke.class cert_renew.class cert_man.class cert_view.class cert_man_op.class result_view.class result_view_op.class nl_reg_cert_op.class


clean:
	rm -f *.class
