include ../../Makefile.conf

all: cert_main.class cert_get.class cert_get_op.class cert_request.class cert_request_op.class \
	cert_replace.class cert_replace_op.class cert_renew.class cert_renew_op.class \
	cert_update.class cert_update_op.class cert_revoke.class cert_revoke_op.class \
	cacert_install.class


clean:
	rm -f *.class
